theme: jekyll-theme-cayman
title: Matematiikkakilpailijat
description: Matematiikan olympiavalmennuksen osallistujien kokemuksia
url: "https://blog.matematiikkakilpailut.fi"
baseurl: "/"
github:
  is_project_page: false
lang: fi
paginate: 20
paginate_path: "/posts/:num/"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
staticman:
  branch: master
facebook:
 app_id: 964806940344711
