theme: jekyll-theme-cayman
title: Matematiikkakilpailijat
description: Matematiikan olympiavalmennuksen osallistujien kokemuksia
url: "https://blog.matematiikkakilpailut.fi"
baseurl: "/"
github:
  is_project_page: false
lang: fi
